# Uncomment the next line to define a global platform for your project
platform :ios, '14.0'

target 'Botticelli' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Botticelli

end

target 'FlicksBox' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for FlicksBox

end

target 'Hermes' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Hermes

end

pod 'SwiftLint', '~>0.43'
